"""
G-Code pretraining data: download, filter, train the code tokenizer, pack.

Runs on a Kaggle CPU session (fast network, no GPU quota). Every stage skips
itself when its output already exists, so a rerun resumes instead of redoing
hours of work.

  1. download   JavaScript + HTML parquet shards of codeparrot/github-code-clean
                (Apache-2.0, ungated) plus a slice of English and Polish prose
  2. filter     drop vendored, generated and minified files
  3. tokenizer  byte-level BPE, 32k, GPT-4 style pre-split so runs of
                indentation become single tokens
  4. pack       uint16 token binaries; half the code documents are rewritten
                into fill-in-the-middle order so the model can also complete
                a gap in the middle of a file, not only the end

Usage:
    python data/prep_pretrain.py --work /kaggle/working
"""

import argparse
import hashlib
import json
import os
import random
import re
import sys
import time
import urllib.request
from pathlib import Path

import numpy as np

DATASET = "codeparrot/github-code-clean"
CONFIGS = {"JavaScript-all": 10, "HTML-all": 10}
PARQUET_URL = "https://huggingface.co/api/datasets/{ds}/parquet/{cfg}/train/{i}.parquet"

SPECIAL_TOKENS = [
    "<|pad|>", "<|endoftext|>",
    "<|fim_prefix|>", "<|fim_middle|>", "<|fim_suffix|>",
    "<|prompt|>", "<|code|>", "<|prev|>", "<|slots|>", "<|file|>",
] + [f"<|reserved_{i}|>" for i in range(6)]

SPLIT_PATTERN = (r"""(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\r\n\p{L}\p{N}]?\p{L}+|\p{N}{1,3}|"""
                 r""" ?[^\s\p{L}\p{N}]+[\r\n]*|\s*[\r\n]+|\s+(?!\S)|\s+""")

BAD_PATH = re.compile(r"(node_modules|bower_components|/vendor/|/vendors/|/dist/|/build/|"
                      r"\.min\.|bundle|/lib/jquery|/polyfill|/assets/js/plugins|"
                      r"-min\.js|/coverage/|/docs?/api/)", re.I)
DOC_SEP = "\n<|gcode-doc|>\n"
FIM_RATE = 0.5
CHUNK_CHARS = 6000


def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def download(work: Path):
    raw = work / "raw"
    raw.mkdir(parents=True, exist_ok=True)
    headers = {"User-Agent": "g-code-prep"}
    if os.environ.get("HF_TOKEN"):
        headers["Authorization"] = f"Bearer {os.environ['HF_TOKEN']}"
    for cfg, n in CONFIGS.items():
        for i in range(n):
            out = raw / f"{cfg}-{i}.parquet"
            if out.exists() and out.stat().st_size > 1_000_000:
                continue
            url = PARQUET_URL.format(ds=DATASET, cfg=cfg, i=i)
            for attempt in range(5):
                try:
                    req = urllib.request.Request(url, headers=headers)
                    with urllib.request.urlopen(req, timeout=120) as r, open(f"{out}.part", "wb") as f:
                        while chunk := r.read(1 << 22):
                            f.write(chunk)
                    os.replace(f"{out}.part", out)
                    log(f"downloaded {out.name}  {out.stat().st_size/1e6:.0f} MB")
                    break
                except Exception as e:
                    log(f"retry {attempt+1} {out.name}: {e}")
                    time.sleep(10 * (attempt + 1))
            else:
                raise SystemExit(f"could not download {url}")


def keep_code(code: str, path: str) -> bool:
    if BAD_PATH.search(path):
        return False
    n = len(code)
    if n < 200 or n > 80_000:
        return False
    lines = code.split("\n")
    if max(len(l) for l in lines) > 400:
        return False
    if n / len(lines) > 90:
        return False
    alnum = sum(c.isalnum() for c in code[:4000]) / min(n, 4000)
    if alnum < 0.25:
        return False
    head = code[:600].lower()
    if "auto-generated" in head or "autogenerated" in head or "do not edit" in head:
        return False
    if code.count("base64,") > 3:
        return False
    return True


def filter_code(work: Path) -> Path:
    out = work / "code.txt"
    done = work / "code.done"
    if done.exists():
        log(f"code.txt already filtered ({out.stat().st_size/1e9:.2f} GB)")
        return out
    import pyarrow.parquet as pq
    seen = set()
    stats = {"rows": 0, "kept": 0, "dupe": 0, "chars": 0}
    with open(out, "w", encoding="utf-8") as f:
        for p in sorted((work / "raw").glob("*.parquet")):
            pf = pq.ParquetFile(p)
            for batch in pf.iter_batches(columns=["code", "path"], batch_size=4096):
                codes = batch.column(0).to_pylist()
                paths = batch.column(1).to_pylist()
                for code, path in zip(codes, paths):
                    stats["rows"] += 1
                    if not code or not keep_code(code, path or ""):
                        continue
                    h = hashlib.md5(re.sub(r"\s+", "", code).encode("utf-8", "ignore")).digest()
                    if h in seen:
                        stats["dupe"] += 1
                        continue
                    seen.add(h)
                    code = code.replace("<|", "< |")
                    name = os.path.basename(path or "file.js")
                    f.write(f"<|file|>{name}\n{code}{DOC_SEP}")
                    stats["kept"] += 1
                    stats["chars"] += len(code)
            log(f"{p.name}: rows {stats['rows']:,} kept {stats['kept']:,} "
                f"dupes {stats['dupe']:,} chars {stats['chars']/1e9:.2f}G")
    done.write_text(json.dumps(stats))
    return out


def fetch_prose(work: Path) -> Path:
    """A little natural language so prompts in both languages tokenise well
    and the model has seen ordinary sentences before instruction tuning."""
    out = work / "prose.txt"
    if out.exists() and out.stat().st_size > 50_000_000:
        log(f"prose.txt present ({out.stat().st_size/1e6:.0f} MB)")
        return out
    from datasets import load_dataset
    sources = [
        ("HuggingFaceFW/fineweb", "sample-10BT", 90_000_000),
        ("HuggingFaceFW/fineweb-2", "pol_Latn", 90_000_000),
    ]
    with open(out, "w", encoding="utf-8") as f:
        for name, cfg, budget in sources:
            ds = load_dataset(name, cfg, split="train", streaming=True)
            used = 0
            for row in ds:
                t = row["text"].strip().replace("<|", "< |")
                if len(t) < 300:
                    continue
                f.write(t + DOC_SEP)
                used += len(t)
                if used >= budget:
                    break
            log(f"prose {name}/{cfg}: {used/1e6:.0f}M chars")
    return out


def iter_docs(path: Path):
    buf = []
    sep = DOC_SEP.strip("\n")
    with open(path, encoding="utf-8", errors="ignore") as f:
        for line in f:
            if line.rstrip("\n") == sep:
                doc = "".join(buf).rstrip("\n")
                buf.clear()
                if doc:
                    yield doc
            else:
                buf.append(line)
    if buf:
        yield "".join(buf).rstrip("\n")


def train_tokenizer(work: Path, code: Path, prose: Path) -> Path:
    out = work / "tokenizer.json"
    if out.exists():
        log("tokenizer.json exists")
        return out
    from tokenizers import Tokenizer, Regex, decoders, pre_tokenizers, trainers
    from tokenizers.models import BPE

    tok = Tokenizer(BPE(unk_token=None, byte_fallback=False))
    tok.pre_tokenizer = pre_tokenizers.Sequence([
        pre_tokenizers.Split(Regex(SPLIT_PATTERN), behavior="isolated"),
        pre_tokenizers.ByteLevel(add_prefix_space=False, use_regex=False),
    ])
    tok.decoder = decoders.ByteLevel()
    trainer = trainers.BpeTrainer(
        vocab_size=32000, special_tokens=SPECIAL_TOKENS,
        initial_alphabet=pre_tokenizers.ByteLevel.alphabet(),
        min_frequency=2, show_progress=False,
    )

    rng = random.Random(0)

    def sample():
        budget = {"code": 900_000_000, "prose": 150_000_000}
        for src, key in ((code, "code"), (prose, "prose")):
            used = 0
            for doc in iter_docs(src):
                if key == "code" and rng.random() > 0.3:
                    continue
                if doc.startswith("<|file|>"):
                    doc = doc.split("\n", 1)[-1]
                yield doc
                used += len(doc)
                if used >= budget[key]:
                    break

    log("training tokenizer ...")
    tok.train_from_iterator(sample(), trainer)
    tok.save(str(out))
    log(f"tokenizer saved, vocab {tok.get_vocab_size()}")
    for s in ["function update(dt) {\n    player.x += speed * dt;\n}",
              "const ball = sphere({ color: 'green' }).jump();",
              "a jumping green sphere", "skacząca zielona kula"]:
        ids = tok.encode(s).ids
        assert tok.decode(ids) == s, f"roundtrip failed: {s!r}"
        log(f"{len(ids):3d} tok / {len(s):3d} ch  {s[:40]!r}")
    return out


def fim(doc: str, rng: random.Random) -> str:
    header = ""
    if doc.startswith("<|file|>"):
        header, doc = doc.split("\n", 1)
        header += "\n"
    if len(doc) < 50:
        return header + doc
    a, b = sorted(rng.sample(range(len(doc) + 1), 2))
    pre, mid, suf = doc[:a], doc[a:b], doc[b:]
    return f"<|fim_prefix|>{header}{pre}<|fim_suffix|>{suf}<|fim_middle|>{mid}"


def chunks(doc: str):
    if len(doc) <= CHUNK_CHARS:
        yield doc
        return
    header = ""
    if doc.startswith("<|file|>"):
        header, doc = doc.split("\n", 1)
        header += "\n"
    lines, cur, size = doc.split("\n"), [], 0
    for line in lines:
        cur.append(line)
        size += len(line) + 1
        if size >= CHUNK_CHARS:
            yield header + "\n".join(cur)
            cur, size = [], 0
    if cur:
        yield header + "\n".join(cur)


def pack(work: Path, code: Path, prose: Path, tok_path: Path, max_tokens: float):
    prefix = work / "gc"
    if (work / "pack.done").exists():
        log("already packed")
        return prefix
    from tokenizers import Tokenizer
    tok = Tokenizer.from_file(str(tok_path))
    eot = tok.token_to_id("<|endoftext|>")
    assert tok.get_vocab_size() <= 65535
    rng = random.Random(1)
    tf, vf = open(f"{prefix}_train.bin", "wb"), open(f"{prefix}_val.bin", "wb")
    counts = {"train": 0, "val": 0, "docs": 0, "fim": 0, "prose": 0}

    def stream():
        prose_iter = iter_docs(prose)
        for i, doc in enumerate(iter_docs(code)):
            for part in chunks(doc):
                if rng.random() < FIM_RATE:
                    counts["fim"] += 1
                    yield fim(part, rng)
                else:
                    yield part
            if i % 12 == 0:
                p = next(prose_iter, None)
                if p:
                    counts["prose"] += 1
                    yield p

    batch = []

    def flush():
        for enc in tok.encode_batch(batch):
            ids = np.asarray(enc.ids + [eot], dtype=np.uint16)
            if counts["docs"] % 200 == 0:
                ids.tofile(vf); counts["val"] += len(ids)
            else:
                ids.tofile(tf); counts["train"] += len(ids)
            counts["docs"] += 1
        batch.clear()

    for doc in stream():
        batch.append(doc)
        if len(batch) >= 2000:
            flush()
            if counts["docs"] % 100_000 < 2000:
                log(f"{counts['docs']:,} docs  {counts['train']/1e6:.0f}M train tokens")
            if counts["train"] >= max_tokens:
                break
    if batch:
        flush()
    tf.close(); vf.close()
    log(f"packed: {json.dumps(counts)}")
    (work / "pack.done").write_text(json.dumps(counts))
    return prefix


def verify(prefix: Path, tok_path: Path):
    from tokenizers import Tokenizer
    tok = Tokenizer.from_file(str(tok_path))
    arr = np.memmap(f"{prefix}_train.bin", dtype=np.uint16, mode="r")
    log(f"train tokens {len(arr):,}  max id {int(arr.max())}")
    assert int(arr.max()) < tok.get_vocab_size()
    mid = len(arr) // 2
    print(tok.decode([int(t) for t in arr[mid:mid + 200]], skip_special_tokens=False)[:1200])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--work", type=Path, default=Path("/kaggle/working"))
    ap.add_argument("--max-tokens", type=float, default=2.6e9)
    args = ap.parse_args()
    args.work.mkdir(parents=True, exist_ok=True)

    download(args.work)
    code = filter_code(args.work)
    prose = fetch_prose(args.work)
    tok = train_tokenizer(args.work, code, prose)
    prefix = pack(args.work, code, prose, tok, args.max_tokens)
    verify(prefix, tok)


if __name__ == "__main__":
    sys.exit(main())
